package net.seichi915.seichi915chat.converter

import org.apache.commons.lang.StringUtils

object RomajiToHiraganaConverter {
  private var romajiAndHiraganaMap = Map(
    "a" -> "あ",
    "i" -> "い",
    "u" -> "う",
    "e" -> "え",
    "o" -> "お",
    "ka" -> "か",
    "ki" -> "き",
    "ku" -> "く",
    "ke" -> "け",
    "ko" -> "こ",
    "sa" -> "さ",
    "si" -> "し",
    "su" -> "す",
    "se" -> "せ",
    "so" -> "そ",
    "ta" -> "た",
    "ti" -> "ち",
    "tu" -> "つ",
    "te" -> "て",
    "to" -> "と",
    "ha" -> "は",
    "hi" -> "ひ",
    "hu" -> "ふ",
    "he" -> "へ",
    "ho" -> "ほ",
    "ma" -> "ま",
    "mi" -> "み",
    "mu" -> "む",
    "me" -> "め",
    "mo" -> "も",
    "ya" -> "や",
    "yu" -> "ゆ",
    "yo" -> "よ",
    "ra" -> "ら",
    "ri" -> "り",
    "ru" -> "る",
    "re" -> "れ",
    "ro" -> "ろ",
    "wa" -> "わ",
    "wo" -> "を",
    "yi" -> "い",
    "wu" -> "う",
    "whu" -> "う",
    "wha" -> "うぁ",
    "whi" -> "うぃ",
    "whe" -> "うぇ",
    "who" -> "うぉ",
    "wyi" -> "ゐ",
    "wye" -> "ゑ",
    "wi" -> "うぃ",
    "we" -> "うぇ",
    "la" -> "ぁ",
    "li" -> "ぃ",
    "lu" -> "ぅ",
    "le" -> "ぇ",
    "lo" -> "ぉ",
    "xa" -> "ぁ",
    "xi" -> "ぃ",
    "xu" -> "ぅ",
    "xe" -> "ぇ",
    "xo" -> "ぉ",
    "ye" -> "いぇ",
    "lyi" -> "ぃ",
    "lye" -> "ぇ",
    "xyi" -> "ぃ",
    "xye" -> "ぇ",
    "ca" -> "か",
    "cu" -> "く",
    "co" -> "こ",
    "qu" -> "く",
    "kya" -> "きゃ",
    "kyi" -> "きぃ",
    "kyu" -> "きゅ",
    "kye" -> "きぇ",
    "kyo" -> "きょ",
    "qya" -> "くゃ",
    "qyi" -> "くぃ",
    "qyu" -> "くゅ",
    "qye" -> "くぇ",
    "qyo" -> "くょ",
    "qwa" -> "くぁ",
    "qwi" -> "くぃ",
    "qwu" -> "くぅ",
    "qwe" -> "くぇ",
    "qwo" -> "くぉ",
    "qa" -> "くぁ",
    "qi" -> "くぃ",
    "qe" -> "くぇ",
    "qo" -> "くぉ",
    "kwa" -> "くぁ",
    "ga" -> "が",
    "gi" -> "ぎ",
    "gu" -> "ぐ",
    "ge" -> "げ",
    "go" -> "ご",
    "gya" -> "ぎゃ",
    "gyi" -> "ぎぃ",
    "gyu" -> "ぎゅ",
    "gye" -> "ぎぇ",
    "gyo" -> "ぎょ",
    "gwa" -> "ぐぁ",
    "gwi" -> "ぐぃ",
    "gwu" -> "ぐぅ",
    "gwe" -> "ぐぇ",
    "gwo" -> "ぐぉ",
    "lka" -> "ヵ",
    "lke" -> "ヶ",
    "xka" -> "ヵ",
    "xke" -> "ヶ",
    "ci" -> "し",
    "ce" -> "せ",
    "shi" -> "し",
    "sya" -> "しゃ",
    "syi" -> "しぃ",
    "syu" -> "しゅ",
    "sye" -> "しぇ",
    "syo" -> "しょ",
    "sha" -> "しゃ",
    "shu" -> "しゅ",
    "she" -> "しぇ",
    "sho" -> "しょ",
    "swa" -> "すぁ",
    "swi" -> "すぃ",
    "swu" -> "すぅ",
    "swe" -> "すぇ",
    "swo" -> "すぉ",
    "za" -> "ざ",
    "zi" -> "じ",
    "zu" -> "ず",
    "ze" -> "ぜ",
    "zo" -> "ぞ",
    "ji" -> "じ",
    "zya" -> "じゃ",
    "zyi" -> "じぃ",
    "zyu" -> "じゅ",
    "zye" -> "じぇ",
    "zyo" -> "じょ",
    "ja" -> "じゃ",
    "jyi" -> "じぃ",
    "ju" -> "じゅ",
    "je" -> "じぇ",
    "jo" -> "じょ",
    "jya" -> "じゃ",
    "jyu" -> "じゅ",
    "jye" -> "じぇ",
    "jyo" -> "じょ",
    "chi" -> "ち",
    "tsu" -> "つ",
    "tya" -> "ちゃ",
    "tyi" -> "ちぃ",
    "tyu" -> "ちゅ",
    "tye" -> "ちぇ",
    "tyo" -> "ちょ",
    "cha" -> "ちゃ",
    "cyi" -> "ちぃ",
    "chu" -> "ちゅ",
    "che" -> "ちぇ",
    "cho" -> "ちょ",
    "cya" -> "ちゃ",
    "cyu" -> "ちゅ",
    "cye" -> "ちぇ",
    "cyo" -> "ちょ",
    "tsa" -> "つぁ",
    "tsi" -> "つぃ",
    "tse" -> "つぇ",
    "tso" -> "つぉ",
    "tha" -> "てゃ",
    "thi" -> "てぃ",
    "thu" -> "てゅ",
    "the" -> "てぇ",
    "tho" -> "てょ",
    "twa" -> "とぁ",
    "twi" -> "とぃ",
    "twu" -> "とぅ",
    "twe" -> "とぇ",
    "two" -> "とぉ",
    "da" -> "だ",
    "di" -> "ぢ",
    "du" -> "づ",
    "de" -> "で",
    "do" -> "ど",
    "dya" -> "ぢゃ",
    "dyi" -> "ぢぃ",
    "dyu" -> "ぢゅ",
    "dye" -> "ぢぇ",
    "dyo" -> "ぢょ",
    "dha" -> "でゃ",
    "dhi" -> "でぃ",
    "dhu" -> "でゅ",
    "dhe" -> "でぇ",
    "dho" -> "でょ",
    "dwa" -> "どぁ",
    "dwi" -> "どぃ",
    "dwu" -> "どぅ",
    "dwe" -> "どぇ",
    "dwo" -> "どぉ",
    "ltu" -> "っ",
    "xtu" -> "っ",
    "ltsu" -> "っ",
    "xtsu" -> "っ",
    "fu" -> "ふ",
    "hya" -> "ひゃ",
    "hyi" -> "ひぃ",
    "hyu" -> "ひゅ",
    "hye" -> "ひぇ",
    "hyo" -> "ひょ",
    "fwa" -> "ふぁ",
    "fwi" -> "ふぃ",
    "fwu" -> "ふぅ",
    "fwe" -> "ふぇ",
    "fwo" -> "ふぉ",
    "fya" -> "ふゃ",
    "fyu" -> "ふゅ",
    "fyo" -> "ふょ",
    "fa" -> "ふぁ",
    "fi" -> "ふぃ",
    "fe" -> "ふぇ",
    "fo" -> "ふぉ",
    "fyi" -> "ふぃ",
    "fye" -> "ふぇ",
    "ba" -> "ば",
    "bi" -> "び",
    "bu" -> "ぶ",
    "be" -> "べ",
    "bo" -> "ぼ",
    "bya" -> "びゃ",
    "byi" -> "びぃ",
    "byu" -> "びゅ",
    "bye" -> "びぇ",
    "byo" -> "びょ",
    "va" -> "ヴぁ",
    "vi" -> "ヴぃ",
    "vu" -> "ヴ",
    "ve" -> "ヴぇ",
    "vo" -> "ヴぉ",
    "vya" -> "ヴゃ",
    "vyi" -> "ヴぃ",
    "vyu" -> "ヴゅ",
    "vye" -> "ヴぇ",
    "vyo" -> "ヴょ",
    "pa" -> "ぱ",
    "pi" -> "ぴ",
    "pu" -> "ぷ",
    "pe" -> "ぺ",
    "po" -> "ぽ",
    "pya" -> "ぴゃ",
    "pyi" -> "ぴぃ",
    "pyu" -> "ぴゅ",
    "pye" -> "ぴぇ",
    "pyo" -> "ぴょ",
    "mya" -> "みゃ",
    "myi" -> "みぃ",
    "myu" -> "みゅ",
    "mye" -> "みぇ",
    "myo" -> "みょ",
    "lya" -> "ゃ",
    "lyu" -> "ゅ",
    "lyo" -> "ょ",
    "xya" -> "ゃ",
    "xyu" -> "ゅ",
    "xyo" -> "ょ",
    "rya" -> "りゃ",
    "ryi" -> "りぃ",
    "ryu" -> "りゅ",
    "rye" -> "りぇ",
    "ryo" -> "りょ",
    "lwa" -> "ゎ",
    "xwa" -> "ゎ",
    "-" -> "ー",
    "," -> "、",
    "[" -> "「",
    "]" -> "」"
  )

  romajiAndHiraganaMap.foreach {
    case (romaji: String, hiragana: String) =>
      if (!StringUtils.startsWithAny(romaji,
                                     Array("a", "i", "u", "e", "o", "n"))) {
        romajiAndHiraganaMap += s"${romaji.charAt(0)}$romaji" -> s"っ$hiragana"
      }
  }

  def convert(romaji: String): String = {
    val replaced =
      romaji
        .replaceAll("nn", "ん")
        .replaceAll("xn", "ん")
        .replaceAll("n'", "ん")
        .replaceAll("na", "な")
        .replaceAll("ni", "に")
        .replaceAll("nu", "ぬ")
        .replaceAll("ne", "ね")
        .replaceAll("no", "の")
        .replaceAll("nya", "にゃ")
        .replaceAll("nyi", "にぃ")
        .replaceAll("nyu", "にゅ")
        .replaceAll("nye", "にぇ")
        .replaceAll("nyo", "にょ")
        .replaceAll("n", "ん")
    StringUtils.replaceEach(replaced,
                            romajiAndHiraganaMap.keySet.toArray[String],
                            romajiAndHiraganaMap.values.toArray[String])
  }
}
